version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: postgres-test-db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5434:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  postgres-test-data:

networks:
  test-network:
    driver: bridge
